### ISSUE TITLE
Problem with text position in treeplot

### ISSUE THREAD

**Issue by DaiqingChen** [YuLab-SMU/biomedical-knowledge-mining-book#12]
I was trying to plot a treeplot for the GOs, but the circle in front of every row is blocking the content. I am also having problem adjusting the position of cluster name on the right. I tried to adjust the text by 'label_format' and 'offset', but it's not very helpful. 
Is there a way to show the full content of cluster names and remove the circle in front of each row?

This is how my plot look like:
![GO in WT_ColdvsKO_Cold](https://user-images.githubusercontent.com/102173866/163827439-a87cd006-0719-421c-8f53-3521d2f880b9.png)

This is the code I used:
treeplot(ego_WT_ColdvsKO_Cold, label_format = 25,fontsize = 4,offset = 3)

**Comment by GuangchuangYu** [comment]
@huerqiang two features requested:

1. label on top
2. support passing `rel` object to offset. (see `?ggplot2::rel`).

**Comment by GuangchuangYu** [comment]
solved, see <https://github.com/YuLab-SMU/enrichplot/pull/175>.
