### ISSUE TITLE
Cell Marker doc example is broken

### ISSUE THREAD

**Issue by hermidalc** [YuLab-SMU/biomedical-knowledge-mining-book#17]
When I try to run https://yulab-smu.top/biomedical-knowledge-mining-book/universal-api.html#cell-marker I get the following error:
```R
cell_marker_data <- vroom::vroom('http://bio-bigdata.hrbmu.edu.cn/CellMarker/download/Human_cell_markers.txt')
New names:                                                                                                                                                      
• `height="30"></td></tr><tr><td` -> `height="30"></td></tr><tr><td...9`
• `class="i"><span` -> `class="i"><span...10`
• `height="30"></td></tr><tr><td` -> `height="30"></td></tr><tr><td...14`
• `class="i"><span` -> `class="i"><span...15`
Rows: 0 Columns: 17
── Column specification ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: " "
chr (17): <html, xmlns="http://www.w3.org/1999/xhtml"><head><meta, http-equiv="Content-Type"content="text/html;, charset=utf-8"/><title>错误-访问被禁止</title><style...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

cells <- cell_marker_data %>%
  dplyr::select(cellName, geneID) %>%
  dplyr::mutate(geneID = strsplit(geneID, ', ')) %>%
  tidyr::unnest()
Error: invalid version specification ‘0.68’
```

**Comment by huerqiang** [comment]
It should be a network problem. You can download `Human_cell_markers.txt` first, and then run `cell_marker_data <- vroom::vroom(Your_path_to_Human_cell_markers.txt)`

**Comment by hermidalc** [comment]
> It should be a network problem. You can download `Human_cell_markers.txt` first, and then run `cell_marker_data <- vroom::vroom(Your_path_to_Human_cell_markers.txt)`

Doesn't work, when I `wget` the path or try via web browser the resulting data is an HTML page with a few Chinese characters.

**Comment by hermidalc** [comment]
Also, do you have Cell Marker data for mouse?

**Comment by huerqiang** [comment]
I just downloaded this file and it works well.
[Human_cell_markers.txt](https://github.com/YuLab-SMU/biomedical-knowledge-mining-book/files/9418130/Human_cell_markers.txt)

![image](https://user-images.githubusercontent.com/48857018/186480954-48fb157d-5fc4-4747-a692-190cde7f9a7e.png)

**Comment by huerqiang** [comment]
You may need to try other download tools. I downloaded it using the Thunder(迅雷 for Chinese).

**Comment by GuangchuangYu** [comment]
A new version is provided in <#21>.
