### ISSUE TITLE
KEGG enrichment analysis - supported organisms

### ISSUE THREAD

**Issue by tzaquin** [YuLab-SMU/biomedical-knowledge-mining-book#23]
First of all, thank you for this great package!

my question,
TLDR: Is there a way to create a custom orgDB for `enrichKEGG()`?

I have been trying to run a kegg enrichment analyis on non-model organisms. So they are not found in the KEGG dbs. I have run the analysis uing the `enricher()` command, with good results. However, downstream visualization are lacking (bar plot and dot plot i can do it by myself, but networks not). I'm asking if there is a way to create an orgDB using the Annotationforge package similar to `enrichGO` so I would be able to use in `enrichKEGG`?

Tank you

**Comment by huerqiang** [comment]
It's not clear to me why you want to create the Orgdb package. If you really want to develop such a package, please refer to Bioconductor's document.

**Comment by GuangchuangYu** [comment]
Maybe this is what you are looking for, https://github.com/YuLab-SMU/createKEGGdb
